# Config for https://github.com/toolmantim/release-drafter
name-template: 'Play JSON $NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'

change-template: '- $TITLE [#$NUMBER] by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
